application: sinmetal-firestore-3
version: 2
runtime: go
api_version: go1.8

instance_class: F2
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 3
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 64

handlers:
- url: /admin/.*
  login: admin
  script: _go_app
- url: /.*
  script: _go_app
